export const AREACATEGORIES = [
  {
    id: 1,
    name: "서울",
    subcategories: [
      { subCategoryId: 1, name: "강남구" },
      { subCategoryId: 2, name: "강동구" },
      { subCategoryId: 3, name: "강북구" },
      { subCategoryId: 4, name: "강서구" },
      { subCategoryId: 5, name: "관악구" },
      { subCategoryId: 6, name: "광진구" },
      { subCategoryId: 7, name: "구로구" },
      { subCategoryId: 8, name: "금천구" },
      { subCategoryId: 9, name: "노원구" },
      { subCategoryId: 10, name: "도봉구" },
      { subCategoryId: 11, name: "동대문구" },
      { subCategoryId: 12, name: "동작구" },
      { subCategoryId: 13, name: "마포구" },
      { subCategoryId: 14, name: "서대문구" },
      { subCategoryId: 15, name: "서초구" },
      { subCategoryId: 16, name: "성동구" },
      { subCategoryId: 17, name: "성북구" },
      { subCategoryId: 18, name: "송파구" },
      { subCategoryId: 19, name: "양천구" },
      { subCategoryId: 20, name: "영등포구" },
      { subCategoryId: 21, name: "용산구" },
      { subCategoryId: 22, name: "은평구" },
      { subCategoryId: 23, name: "종로구" },
      { subCategoryId: 24, name: "중구" },
      { subCategoryId: 25, name: "중랑구" },
    ]
  },
  {
    id: 2,
    name: "부산",
    subcategories: [
      { subCategoryId: 26, name: "강서구" },
      { subCategoryId: 27, name: "금정구" },
      { subCategoryId: 28, name: "기장군" },
      { subCategoryId: 29, name: "남구" },
      { subCategoryId: 30, name: "동구" },
      { subCategoryId: 31, name: "동래구" },
      { subCategoryId: 32, name: "부산진구" },
      { subCategoryId: 33, name: "북구" },
      { subCategoryId: 34, name: "사상구" },
      { subCategoryId: 35, name: "사하구" },
      { subCategoryId: 36, name: "서구" },
      { subCategoryId: 37, name: "수영구" },
      { subCategoryId: 38, name: "연제구" },
      { subCategoryId: 39, name: "영도구" },
      { subCategoryId: 40, name: "중구" },
      { subCategoryId: 41, name: "해운대구" },
    ]
  },
  {
    id: 3,
    name: "대구",
    subcategories: [
      { subCategoryId: 42, name: "남구" },
      { subCategoryId: 43, name: "달서구" },
      { subCategoryId: 44, name: "동구" },
      { subCategoryId: 45, name: "북구" },
      { subCategoryId: 46, name: "서구" },
      { subCategoryId: 47, name: "수성구" },
      { subCategoryId: 48, name: "중구" },
      { subCategoryId: 49, name: "달성군" },
    ]
  },
  {
    id: 4,
    name: "인천",
    subcategories: [
      { subCategoryId: 50, name: "계양구" },
      { subCategoryId: 51, name: "미추홀구" },
      { subCategoryId: 52, name: "남동구" },
      { subCategoryId: 53, name: "동구" },
      { subCategoryId: 54, name: "부평구" },
      { subCategoryId: 55, name: "서구" },
      { subCategoryId: 56, name: "연수구" },
      { subCategoryId: 57, name: "중구" },
      { subCategoryId: 58, name: "강화군" },
      { subCategoryId: 59, name: "옹진군" },
    ]
  },
  {
    id: 5,
    name: "광주",
    subcategories: [
      { subCategoryId: 60, name: "광산구" },
      { subCategoryId: 61, name: "남구" },
      { subCategoryId: 62, name: "동구" },
      { subCategoryId: 63, name: "북구" },
      { subCategoryId: 64, name: "서구" },
    ]
  },
  {
    id: 6,
    name: "대전",
    subcategories: [
      { subCategoryId: 65, name: "대덕구" },
      { subCategoryId: 66, name: "동구" },
      { subCategoryId: 67, name: "서구" },
      { subCategoryId: 68, name: "유성구" },
      { subCategoryId: 69, name: "중구" },
    ]
  },
  {
    id: 7,
    name: "울산",
    subcategories: [
      { subCategoryId: 70, name: "남구" },
      { subCategoryId: 71, name: "동구" },
      { subCategoryId: 72, name: "북구" },
      { subCategoryId: 73, name: "중구" },
      { subCategoryId: 74, name: "울주군" },
    ]
  },
  {
    id: 8,
    name: "세종",
    subcategories: [
      { subCategoryId: 75, name: "" },
    ]
  },
  {
    id: 9,
    name: "경기",
    subcategories: [
      { subCategoryId: 76, name: "고양시" },
      { subCategoryId: 77, name: "과천시" },
      { subCategoryId: 78, name: "광명시" },
      { subCategoryId: 79, name: "광주시" },
      { subCategoryId: 80, name: "구리시" },
      { subCategoryId: 81, name: "군포시" },
      { subCategoryId: 82, name: "김포시" },
      { subCategoryId: 83, name: "남양주시" },
      { subCategoryId: 84, name: "동두천시" },
      { subCategoryId: 85, name: "부천시" },
      { subCategoryId: 86, name: "성남시" },
      { subCategoryId: 87, name: "수원시" },
      { subCategoryId: 88, name: "시흥시" },
      { subCategoryId: 89, name: "안산시" },
      { subCategoryId: 90, name: "안성시" },
      { subCategoryId: 91, name: "안양시" },
      { subCategoryId: 92, name: "양주시" },
      { subCategoryId: 93, name: "여주시" },
      { subCategoryId: 94, name: "오산시" },
      { subCategoryId: 95, name: "의왕시" },
      { subCategoryId: 96, name: "의정부시" },
      { subCategoryId: 97, name: "이천시" },
      { subCategoryId: 98, name: "파주시" },
      { subCategoryId: 99, name: "평택시" },
      { subCategoryId: 100, name: "포천시" },
      { subCategoryId: 101, name: "하남시" },
      { subCategoryId: 102, name: "화성시" },
      { subCategoryId: 103, name: "가평군" },
      { subCategoryId: 104, name: "양평군" },
      { subCategoryId: 105, name: "연천구" },
    ]
  },
  {
    id: 10,
    name: "강원",
    subcategories: [
      { subCategoryId: 106, name: "강릉시" },
      { subCategoryId: 107, name: "동해시" },
      { subCategoryId: 108, name: "삼척시" },
      { subCategoryId: 109, name: "속초시" },
      { subCategoryId: 110, name: "원주시" },
      { subCategoryId: 111, name: "춘천시" },
      { subCategoryId: 112, name: "태백시" },
      { subCategoryId: 113, name: "고성군" },
      { subCategoryId: 114, name: "양구군" },
      { subCategoryId: 115, name: "양양군" },
      { subCategoryId: 116, name: "영월군" },
      { subCategoryId: 117, name: "인제군" },
      { subCategoryId: 118, name: "정선군" },
      { subCategoryId: 119, name: "철원군" },
      { subCategoryId: 120, name: "평창군" },
      { subCategoryId: 121, name: "홍천군" },
      { subCategoryId: 122, name: "화천군" },
      { subCategoryId: 123, name: "횡성군" },
    ]
  },
  {
    id: 11,
    name: "충북",
    subcategories: [
      { subCategoryId: 124, name: "제천시" },
      { subCategoryId: 125, name: "청주시" },
      { subCategoryId: 126, name: "충주시" },
      { subCategoryId: 127, name: "괴산군" },
      { subCategoryId: 128, name: "단양군" },
      { subCategoryId: 129, name: "보은군" },
      { subCategoryId: 130, name: "영동군" },
      { subCategoryId: 131, name: "옥천군" },
      { subCategoryId: 132, name: "음성군" },
      { subCategoryId: 133, name: "증평군" },
      { subCategoryId: 134, name: "진천군" },
    ]
  },
  {
    id: 12,
    name: "충남",
    subcategories: [
      { subCategoryId: 135, name: "계룡시" },
      { subCategoryId: 136, name: "공주시" },
      { subCategoryId: 137, name: "논산시" },
      { subCategoryId: 138, name: "당진시" },
      { subCategoryId: 139, name: "보령시" },
      { subCategoryId: 140, name: "서산시" },
      { subCategoryId: 141, name: "아산시" },
      { subCategoryId: 142, name: "천안시" },
      { subCategoryId: 143, name: "금산군" },
      { subCategoryId: 144, name: "부여군" },
      { subCategoryId: 145, name: "서천군" },
      { subCategoryId: 146, name: "예산군" },
      { subCategoryId: 147, name: "청양군" },
      { subCategoryId: 148, name: "태안군" },
      { subCategoryId: 149, name: "홍성군" },
    ]
  },
  {
    id: 13,
    name: "전북",
    subcategories: [
      { subCategoryId: 150, name: "군산시" },
      { subCategoryId: 151, name: "김제시" },
      { subCategoryId: 152, name: "남원시" },
      { subCategoryId: 153, name: "익산시" },
      { subCategoryId: 154, name: "전주시" },
      { subCategoryId: 155, name: "정읍시" },
      { subCategoryId: 156, name: "고창군" },
      { subCategoryId: 157, name: "무주군" },
      { subCategoryId: 158, name: "부안군" },
      { subCategoryId: 159, name: "순창군" },
      { subCategoryId: 160, name: "완주군" },
      { subCategoryId: 161, name: "임실군" },
      { subCategoryId: 162, name: "장수군" },
      { subCategoryId: 163, name: "진안구" },
    ]
  },
  {
    id: 14,
    name: "전남",
    subcategories: [
      { subCategoryId: 164, name: "광양시" },
      { subCategoryId: 165, name: "나주시" },
      { subCategoryId: 166, name: "목포시" },
      { subCategoryId: 167, name: "순천시" },
      { subCategoryId: 168, name: "여수시" },
      { subCategoryId: 169, name: "강진군" },
      { subCategoryId: 170, name: "고흥군" },
      { subCategoryId: 171, name: "곡성군" },
      { subCategoryId: 172, name: "구례군" },
      { subCategoryId: 173, name: "담양군" },
      { subCategoryId: 174, name: "무안군" },
      { subCategoryId: 175, name: "보성군" },
      { subCategoryId: 177, name: "신안군" },
      { subCategoryId: 178, name: "영광군" },
      { subCategoryId: 179, name: "영암군" },
      { subCategoryId: 180, name: "완도군" },
      { subCategoryId: 181, name: "장성군" },
      { subCategoryId: 182, name: "장흥군" },
      { subCategoryId: 183, name: "진도군" },
      { subCategoryId: 184, name: "함평군" },
      { subCategoryId: 185, name: "해남군" },
      { subCategoryId: 186, name: "화순군" },
    ]
  },
  {
    id: 15,
    name: "경북",
    subcategories: [
      { subCategoryId: 187, name: "경산시" },
      { subCategoryId: 188, name: "경주시" },
      { subCategoryId: 189, name: "구미시" },
      { subCategoryId: 190, name: "김천시" },
      { subCategoryId: 191, name: "문경시" },
      { subCategoryId: 192, name: "상주시" },
      { subCategoryId: 193, name: "안동시" },
      { subCategoryId: 194, name: "영주시" },
      { subCategoryId: 195, name: "영천시" },
      { subCategoryId: 196, name: "포항시" },
      { subCategoryId: 197, name: "고령군" },
      { subCategoryId: 198, name: "군위군" },
      { subCategoryId: 199, name: "봉화군" },
      { subCategoryId: 200, name: "성주군" },
      { subCategoryId: 201, name: "영덕군" },
      { subCategoryId: 202, name: "영양군" },
      { subCategoryId: 203, name: "예천군" },
      { subCategoryId: 204, name: "울릉군" },
      { subCategoryId: 205, name: "울진군" },
      { subCategoryId: 206, name: "의성군" },
      { subCategoryId: 207, name: "청도군" },
      { subCategoryId: 208, name: "청송군" },
      { subCategoryId: 209, name: "칠곡군" },
    ]
  },
  {
    id: 16,
    name: "경남",
    subcategories: [
      { subCategoryId: 210, name: "거제시" },
      { subCategoryId: 211, name: "김해시" },
      { subCategoryId: 212, name: "밀양시" },
      { subCategoryId: 213, name: "사천시" },
      { subCategoryId: 214, name: "양산시" },
      { subCategoryId: 215, name: "진주시" },
      { subCategoryId: 216, name: "창원시" },
      { subCategoryId: 217, name: "통영시" },
      { subCategoryId: 218, name: "거창군" },
      { subCategoryId: 219, name: "고성군" },
      { subCategoryId: 220, name: "남해군" },
      { subCategoryId: 221, name: "산청군" },
      { subCategoryId: 222, name: "의령군" },
      { subCategoryId: 223, name: "창녕군" },
      { subCategoryId: 224, name: "하동군" },
      { subCategoryId: 225, name: "함안군" },
      { subCategoryId: 226, name: "함양군" },
      { subCategoryId: 227, name: "합천군" },
    ]
  },
  {
    id: 17,
    name: "제주",
    subcategories: [
      { subCategoryId: 228, name: "서귀포시" },
      { subCategoryId: 229, name: "제주시" },
    ]
  },
]